### ISSUE TITLE
FROM TRELLO : "Fix default color preset not triggering color change."

### ISSUE THREAD

**Issue by KodaRayTominus** [DaDevFox/KCMods#1]
What I assume to be the default color scheme(dark) becomes another scheme(pale) and will not revert using reset or the default drop-down. 

Upon further testing, the issue seems linked to the reset function itself.

Further investigated has revealed varying values as defaults within the code. One pale, one dark. 

I have made two branches to sort out this discrepancy. 

While in the color settings, I also added in the Rocky scheme from the live workshop version.

**Comment by KodaRayTominus** [comment]
https://github.com/KodaRayTominus/KCMods/tree/KodaRayTominus-patch-1(Dark)
https://github.com/KodaRayTominus/KCMods/tree/KodaRayTominus-patch-2(Pale/Light)

**Comment by DaDevFox** [comment]
Thank you for coming up with a solution, I'm very grateful as I didn't have the time to fix this myself. I will merge this as soon as I can and it will be added to the next release build, many thanks!

While this is great the next release has been incredibly backed up by issues so it may be some time before this change makes it into the mod.
