### ISSUE TITLE
POSSIBLE CONFLICTION : Issues running with "New Lands" on sizes 115 and up.

### ISSUE THREAD

**Issue by KodaRayTominus** [DaDevFox/KCMods#2]
Game crashes when placing a Keep on a new map, when using both "New Lands" and "Elevation". 

Upon further investigation issue seems to involve the "New Lands" map size with "Elevation".

Expanding on this further, you can start and place a Keep on maps size 115 and lower. Sometimes 116 works. Possibly related to total assets being placed.

**Comment by KodaRayTominus** [comment]
Further investigation - Even size 115 will crash upon keep being placed.

Found other instances of the bug occurring. 

Also found a note of a "fix" which may have caused this bug. See below.

"Pathfinding Pruning
Unfortunately, a side-effect of this new pathfinding system is that it exposed some minor oversights in the game pathfinding. Normally when a peasant is travelling to a cell that's unreachable, the game tries to path it anyway, resulting in it trying to search a large portion of the map and eventually failing, but with more terrain to try and path around, when this happens with the mod, it causes significant lag (this is the same issue that New Lands struggles with due to the large size of the maps).

How I tried to prevent this is using an algorithm that searches the map for any tiles that should be blocked, and marking them as 'blocked'. Then, I changed how the pathfinding works to avoid these blocked tiles. The algorithm doesn't know where to start the search however, which means it'll search for blocked tiles the moment you place your Keep, or an Outpost if you're colonizing an island.

This **_### might result in a burst of lag once you place the Keep or an Outpost_**, but I feel it's better than continuous lag throughout the game."

**Comment by KodaRayTominus** [comment]
[HarmonyPatch(typeof(Keep), "OnBuildingPlacement")]
        static class OnKeepBuiltPatch
        {
            static void Postfix(Keep __instance)
            {
                Building b = __instance.GetComponent<Building>();
                List<Cell> cells = new List<Cell>();

                b.ForEachTileInBounds(
                    (x, z, cell) =>
                    {
                        cells.Add(cell);
                    });


                BeginSearchPositions.AddRange(cells.AsEnumerable());
                DoRegionSearch();
            }
        }


        [HarmonyPatch(typeof(Outpost), "OnBuildingPlacement")]
        static class OnOutpostBuiltPatch
        {
            static void Postfix(Outpost __instance)
            {
                Building b = __instance.GetComponent<Building>();
                List<Cell> cells = new List<Cell>();

                b.ForEachTileInBounds(
                    (x, z, cell) =>
                    {
                        cells.Add(cell);
                    });


                BeginSearchPositions.AddRange(cells.AsEnumerable());
                DoRegionSearch();
            }
        }

**Comment by KodaRayTominus** [comment]
Commenting out "DoRegionSearch();" Fixes the issue.

**Comment by KodaRayTominus** [comment]
Need to test if Pathing AI breaks with this change.

**Comment by KodaRayTominus** [comment]
Confirmed Pathing AI works after this change.

**Comment by KodaRayTominus** [comment]
The GitHub version has removed this block of code already. The live workshop version still contains it.

**Comment by DaDevFox** [comment]
Yes, it's not the code inherently that causes this problem just the fact that searching on such a large map can often take more memory than a decent computer can handle so it crashes, so I've disabled it on the dev build and it will remain disabled for release, although it can be enabled as a setting
