### ISSUE TITLE
POSSIBLE CONFLICTION : FPS Drops significantly when using "New Lands"

### ISSUE THREAD

**Issue by KodaRayTominus** [DaDevFox/KCMods#3]
Major FPS drop when using the "New Lands" mod.

**Comment by KodaRayTominus** [comment]
Looking into issue, found a note of this possibly being a Pathing AI issue with the main game. 

Possible fix  - overwrite main ai.

**Comment by DaDevFox** [comment]
I think this is not directly an incompatibility, the large lag spike at the beginning of the game when the player places their keep (which is what I think you're referring to) is an algorithm that searches the map for unreachable regions and marks them so the pathing will avoid them later, it's an optimization that allows the pathing to be faster for the duration of the game, at the cost of a one-time lag at the beginning. 
On large maps, and especially with the New Lands mod this becomes exponentially more resource intensive and often leads to crashes, so I've disabled it temporarily in the next release build and I'm planning on making it an option.

**Comment by DaDevFox** [comment]
Resolved -- Path pruning disabled (no longer necessary)
